# 4 Feature Selection and Feature Engineering

In [53]:
import numpy as np 
import pandas as pd
from pathlib import Path

project_root = Path.cwd().parent
raw_data_directory_path = project_root / "data" / "raw"
processed_data_directory_path = project_root / "data" / "processed"

## 4.1. Reshaping to customer grain

The first step is to load the necessary data. In order to engineer features for the e-commerce dataset, the cleaned dataset will be used alongside the dataset containing the cancelled transactions. This is necessary in order to take into account the various customer behaviours and calculate features related to order cancellations.

In [54]:
df = pd.read_csv(processed_data_directory_path / "e-commerce-data-cleaned.csv", encoding = "ISO-8859-1")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 391068 entries, 0 to 391067
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   invoice_number    391068 non-null  int64
 1   stock_code        391068 non-null  str
 2   description       391068 non-null  str
 3   quantity          391068 non-null  int64
 4   invoice_datetime  391068 non-null  str
 5   invoice_date      391068 non-null  str
 6   invoice_time      391068 non-null  str
 7   unit_price        391068 non-null  float64
 8   customer_id       391068 non-null  float64
 9   country           391068 non-null  str
dtypes: float64(2), int64(2), str(6)
memory usage: 60.4 MB

In [55]:
df_canceled = pd.read_csv(processed_data_directory_path / "e-commerce-data-canceled.csv", encoding = "ISO-8859-1")
df_canceled.info()

<class 'pandas.DataFrame'>
RangeIndex: 8872 entries, 0 to 8871
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   invoice_number    8872 non-null   str
 1   stock_code        8872 non-null   str
 2   description       8872 non-null   str
 3   quantity          8872 non-null   int64
 4   invoice_datetime  8872 non-null   str
 5   invoice_date      8872 non-null   str
 6   invoice_time      8872 non-null   str
 7   unit_price        8872 non-null   float64
 8   customer_id       8872 non-null   float64
 9   country           8872 non-null   str
dtypes: float64(2), int64(1), str(7)
memory usage: 1.4 MB

For more convenient work, the next step is to merge the uploaded datasets.

In [56]:
df_new = pd.concat([df, df_canceled], axis = 0, ignore_index = True)
df_new.info()

<class 'pandas.DataFrame'>
RangeIndex: 399940 entries, 0 to 399939
Data columns (total 10 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   invoice_number    399940 non-null  object
 1   stock_code        399940 non-null  str
 2   description       399940 non-null  str
 3   quantity          399940 non-null  int64
 4   invoice_datetime  399940 non-null  str
 5   invoice_date      399940 non-null  str
 6   invoice_time      399940 non-null  str
 7   unit_price        399940 non-null  float64
 8   customer_id       399940 non-null  float64
 9   country           399940 non-null  str
dtypes: float64(2), int64(1), object(1), str(6)
memory usage: 61.8+ MB

In [57]:
df_new

,invoice_number,stock_code,description,quantity,invoice_datetime,invoice_date,invoice_time,unit_price,customer_id,country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2010-12-01,08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,2010-12-01,08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2010-12-01,08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,2010-12-01,08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,2010-12-01,08:26:00,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...,...,...
399935,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,2011-12-09,09:57:00,0.83,14397.0,United Kingdom
399936,C581499,M,Manual,-1,2011-12-09 10:28:00,2011-12-09,10:28:00,224.69,15498.0,United Kingdom
399937,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,2011-12-09,11:57:00,10.95,15311.0,United Kingdom
399938,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,2011-12-09,11:58:00,1.25,17315.0,United Kingdom
399939,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,2011-12-09,11:58:00,1.25,17315.0,United Kingdom

Therefore, the received dataset for this stage of work contains $399940$ records of transactions (both completed and cancelled)

Since feature engineering is being performed as part of a customer segmentation project, the dataset will be **reframed to the customer grain**. In order to determine the number of unique records that will be included in the subsequent feature dataset, the number of unique `customer_id` parameter is calculated.

In [58]:
unique_customer_ids = df_new['customer_id'].nunique()
print(f"Number of unique customer IDs: {unique_customer_ids}")

Number of unique customer IDs: 4370

Thus, a total of $4370$ unique customers were obtained.

Before creating features, a parameter — `snapshot_date` should be created. This is necessary for the 'Recency' feature and its derivatives, such as Customer Tenure, Purchase Velocity, 'Time-Bound Spend', e.t.c.

In [59]:
df_new['invoice_datetime'] = pd.to_datetime(df_new['invoice_datetime'])
df_new['customer_id'] = df_new['customer_id'].astype(object)
snapshot_date = df_new['invoice_datetime'].max() + pd.Timedelta(days = 1)
snapshot_date

Timestamp('2011-12-10 12:50:00')

After creating a snapshot date, the next step is to create basic RFM parameters:
1. `inactive_days` - recency feature;
2. `number_of_transactions` - Frequency feature;
3. `total_spent` - Monetary feature.

In [60]:
df_new['total_amount'] = df_new['quantity'] * df_new['unit_price']

feature_df = df_new.groupby('customer_id').agg(
    inactive_days  = ('invoice_datetime', lambda x: (snapshot_date - x.max()).days),
    number_of_transactions = ('invoice_number', 'nunique'),
    total_spent  = ('total_amount', 'sum')
).reset_index()

feature_df

      customer_id  inactive_days  number_of_transactions  total_spent
0         12346.0            326                       2         0.00
1         12347.0              2                       7      4310.00
2         12348.0             75                       4      1437.24
3         12349.0             19                       1      1457.55
4         12350.0            310                       1       294.40
...           ...            ...                     ...          ...
4365      18280.0            278                       1       180.60
4366      18281.0            181                       1        80.82
4367      18282.0              8                       3       176.60
4368      18283.0              4                      16      2039.58
4369      18287.0             43                       3      1837.28

[4370 rows x 4 columns]

Based on the previous analysis, next step is creating the following features:
- `tenure_days` - the number of days between the first and last transaction for each customer.
- `total_product_quantity` - the total quantity of products purchased by each customer.

In [61]:

feature_df = feature_df.merge(
    df_new.groupby('customer_id').agg(
        tenure_days = ('invoice_datetime', lambda x: (x.max() - x.min()).days),
        total_product_quantity = ('quantity', 'sum')
    ).reset_index(),
    on='customer_id'
)
feature_df

,customer_id,inactive_days,number_of_transactions,total_spent,tenure_days,total_product_quantity
0,12346.0,326,2,0.00,0,0
1,12347.0,2,7,4310.00,365,2458
2,12348.0,75,4,1437.24,282,2332
3,12349.0,19,1,1457.55,0,630
4,12350.0,310,1,294.40,0,196
...,...,...,...,...,...,...
4365,18280.0,278,1,180.60,0,45
4366,18281.0,181,1,80.82,0,54
4367,18282.0,8,3,176.60,118,98
4368,18283.0,4,16,2039.58,333,1355
4369,18287.0,43,3,1837.28,158,1586

With data on canceled orders available, it is possible to use it to create the next features - `canceled_transactions`, and `cancellation_rate`.

In [62]:
df_new['is_canceled'] = (df_new['invoice_number'].astype(str).str.startswith('C')) | (df_new['quantity'] < 0)

canceled_aggregate = (
    df_new[df_new['is_canceled']]
    .groupby('customer_id')['invoice_number'].nunique()
    .rename('canceled_transactions')
    .reset_index()
)

feature_df = feature_df.merge(canceled_aggregate, on = 'customer_id', how = 'left')
feature_df['canceled_transactions'] = feature_df['canceled_transactions'].fillna(0).astype(int)
feature_df['cancellation_rate'] = feature_df['canceled_transactions'] / feature_df['number_of_transactions']

feature_df

,customer_id,inactive_days,number_of_transactions,total_spent,tenure_days,total_product_quantity,canceled_transactions,cancellation_rate
0,12346.0,326,2,0.00,0,0,1,0.500000
1,12347.0,2,7,4310.00,365,2458,0,0.000000
2,12348.0,75,4,1437.24,282,2332,0,0.000000
3,12349.0,19,1,1457.55,0,630,0,0.000000
4,12350.0,310,1,294.40,0,196,0,0.000000
...,...,...,...,...,...,...,...,...
4365,18280.0,278,1,180.60,0,45,0,0.000000
4366,18281.0,181,1,80.82,0,54,0,0.000000
4367,18282.0,8,3,176.60,118,98,1,0.333333
4368,18283.0,4,16,2039.58,333,1355,0,0.000000
4369,18287.0,43,3,1837.28,158,1586,0,0.000000

Based on an analysis of geographic data showing that most customers are from the United Kingdom, the feature `is_UK` can be created. The first step before creating a feature is to check if customers may have multiple countries in their transactions.

In [63]:
multi = df_new.groupby('customer_id')['country'].nunique()
print((multi > 1).sum())

8

Since there are 8 users with multiple countries listed, the most recent geographic location will be used when creating the feature.

In [64]:
latest_country = (
    df_new.sort_values('invoice_datetime')
    .groupby('customer_id')['country'].last()
)

feature_df['is_UK'] = feature_df['customer_id'].map(latest_country).eq('United Kingdom').astype(int)

feature_df

,customer_id,inactive_days,number_of_transactions,total_spent,tenure_days,total_product_quantity,canceled_transactions,cancellation_rate,is_UK
0,12346.0,326,2,0.00,0,0,1,0.500000,1
1,12347.0,2,7,4310.00,365,2458,0,0.000000,0
2,12348.0,75,4,1437.24,282,2332,0,0.000000,0
3,12349.0,19,1,1457.55,0,630,0,0.000000,0
4,12350.0,310,1,294.40,0,196,0,0.000000,0
...,...,...,...,...,...,...,...,...,...
4365,18280.0,278,1,180.60,0,45,0,0.000000,1
4366,18281.0,181,1,80.82,0,54,0,0.000000,1
4367,18282.0,8,3,176.60,118,98,1,0.333333,1
4368,18283.0,4,16,2039.58,333,1355,0,0.000000,1
4369,18287.0,43,3,1837.28,158,1586,0,0.000000,1

In [65]:
feature_df_info = feature_df.set_index('customer_id')
feature_df_info.describe().round(2).T

,count,mean,std,min,25%,50%,75%,max
inactive_days,4370.0,92.19,100.88,1.00,17.00,50.00,143.00,374.00
number_of_transactions,4370.0,5.05,9.27,1.00,1.00,3.00,5.00,245.00
total_spent,4370.0,1859.80,8146.51,-4287.63,289.35,634.48,1562.20,278421.02
tenure_days,4370.0,133.26,132.89,0.00,0.00,97.00,255.75,373.00
total_product_quantity,4370.0,1114.11,4657.83,-303.00,151.00,363.00,955.00,196072.00
canceled_transactions,4370.0,0.84,2.14,0.00,0.00,0.00,1.00,47.00
cancellation_rate,4370.0,0.11,0.18,0.00,0.00,0.00,0.20,1.00
is_UK,4370.0,0.90,0.30,0.00,1.00,1.00,1.00,1.00

|№|Feature|Formula|Feature Group|Description|
|:-:|:--------------|:-------------|:--------------------|:------------------------|
|1  |`inactive_days`            |`(snapshot_date - max(invoice_datetime)).days `                |Recency                |Number of days since the last purchase|
|2  |`number_of_transactions`   |`nunique(invoice_number)`                                      |Frequency              |Number of unique transactions made by a specific customer, in other words, customer activity|
|3  |`total_spent`              |`sum(quantity × unit_price)`                                   |Monetary               |The total amount spent by the customer during the time period covered by the dataset|
|4  |`tenure_days`              |`max(invoice_datetime) - min(invoice_datetime).days`           |Recency                |Number of days that shows how long the customer has been active since the last purchase|
|5  |`total_product_quantity`   |`sum(quantity)`                                                |Frequency              |Amount of product purchased by the unique customer, including canceled transactions|
|6  |`canceled_transactions`    |`nunique(invoice_number) where invoice_number starts with 'C'` |Cancellation behavior  |Number of transactions that have been canceled by a specific customer|
|7  |`cancellation_rate`        |`canceled_transactions / number_of_transactions`               |Cancellation behavior  |Rate of cancelled transactions relative to total transactions for specific customer|
|8  |`is_UK`                    |`country == 'United Kingdom'`                                  |Geographic             |A binary parameter that determines whether the customer is located in the United Kingdom|